create table public.leaderboard (
  id bigint generated by default as identity primary key,
  nickname text not null check (char_length(nickname) between 3 and 15),
  nickname_key text generated always as (lower(nickname)) stored,
  score integer not null check (score between 0 and 1000000),
  created_at timestamptz not null default now(),
  constraint leaderboard_nickname_key_unique unique (nickname_key)
);

alter table public.leaderboard enable row level security;
create policy "Anyone can read leaderboard" on public.leaderboard for select using (true);
revoke insert, update, delete on public.leaderboard from anon, authenticated;
grant select on public.leaderboard to anon, authenticated;